basedir: /

# html lang
language: "it"

# main menu navigation
menu:
  # scommentare per generare pagina
  welcome: welcome
  # welcome/cfp.html: call for paper
  talks_speakers: talk e speaker
  # menu item for workshop
  # workshop: workshop
  sponsor: sponsor

# workshops submenu (comment out if only one workshop: add items for multiple workshops)
workshop_submenu:
#  font_variabili: Tipografia web e font variabili
#   workshop_2: sample second workshop

# welcome submenu
welcome_submenu:
  # cfp: call for paper
  about: about
  coc: codice di condotta
#  safety: salute pubblica
  scholarships: borse di studio
  where: dove e come
  # delete this row to take out of the menu
#  cfp: call for paper

# stylesheets loaded in the <head>
stylesheets:
  - /assets/css/global.css

# scripts loaded in the end of the body / commented out to prevent errors in compiling layout.pug
scripts:
  - /assets/js/menu.js
